# Generated by Django 3.0.7 on 2020-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boast_or_roast',
            field=models.BooleanField(default=None, help_text='Boast if checked'),
        ),
    ]
